/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#include "base.h"
#include "gpio.h"
#include "usart.h"
#include "rcc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	/*Enable AHB1 Clock*/
	RCC->AHB1ENR |= (0x1UL << 0);	//GPIOAEN
	RCC->AHB1ENR |= (0x1UL << 2);	//GPIOCEN

	/*Enable APB1 Clock*/
	RCC->APB1ENR |= (0x1UL <<17);	//USART2EN

	GPIOC->MODER &= ~(3UL<<(13*2)); // PC13
	GPIOC->MODER |=  (1UL<<(13*2)); // set as an output

	GPIOA->MODER &= ~(3UL<<(2*2) | 3UL<<(3*2));  //PA2 and PA3 clear bits
	GPIOA->MODER |=  (2UL<<(2*2) | 2UL<<(3*2));	 //PA2 and PA3 set as an Alternate Function

	GPIOA->AFRL &=  ~(0xFUL<<(2*4) | 0xFUL<<(3*4));
	GPIOA->AFRL |=   (0x7UL<<(2*4) | 0x7UL<<(3*4));

	USART2->BRR = 0x683;

	USART2->CR1 &= ~((1UL<<12) | (1UL<<10) | (1UL<<15)); // M=0, PCE=0, OVER8=0

	USART2->CR2 &= ~(3UL<<12); // STOP[1:0] = 00

	USART2->CR1 |=  ((1UL<<2) | (1UL<<3)); // TE=1 RE=1

	USART2->CR1  |=  (1UL<<13); // UE=1


    /* Loop forever */
	for(;;){


		while(!(USART2->SR & (1UL<<5))){

					// wait until RXTNE=1
				}

			uint32_t sr = USART2->SR;

			uint8_t veri = (uint8_t)(USART2->DR & 0xFF);

			 if (sr & ((1UL << 3) | (1UL << 2) | (1UL << 1) | (1UL << 0))){
				// if there is a corrupt byte
			}

			 else{
				 while(!(USART2->SR & (1UL<<7))){

				 	// wait until TXE=1
				 			}

				 USART2->DR = veri;

			while(!(USART2->SR & (1UL<<6))){

				 		// wait until TC=1
				 	}

				 /* Clear bit 6: TC flag */
				 USART2->SR &= ~(1UL << 6);
		}

	}
}


